version: '3.8'

services:
  backend:
    build:
      context: ./flask_react_app
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
