name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask_react_app/requirements.txt

    - name: Run Python tests
      run: |
        cd flask_react_app
        python -m unittest test_app.py

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: |
        cd client
        npm ci

    - name: Build React app
      run: |
        cd client
        npm run build

    - name: Run React tests
      run: |
        cd client
        npm test -- --watchAll=false

    # Add deployment steps here if needed